-- AlterTable
ALTER TABLE "Cohort" ALTER COLUMN "endDate" DROP NOT NULL,
ALTER COLUMN "endDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "startDate" DROP NOT NULL,
ALTER COLUMN "startDate" SET DEFAULT CURRENT_TIMESTAMP;
