name: CI
on: [push, pull_request]
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SHADOW_DATABASE_URL: ${{ secrets.SHADOW_DATABASE_URL }}
  JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
  JWT_EXPIRY: ${{ secrets.JWT_EXPIRY }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npx eslint src
      - run: npx prisma migrate reset --force --skip-seed
